export { default as evchargerBlue } from "./EV-Logo-Blue2.png";
export { default as evleaf } from "./EVLeaf.png";
export { default as evleaf1 } from "./EVLeaf1.png";
export { default as ev2d } from "./2DEV.png";
export { default as solarroof } from "./SolarRoof.png";
export { default as solarroofgreen } from "./SolarRoofGreen.png";
export { default as evchargecar } from "./evchargecare.png";
export { default as EDLLogo } from "./logo.png";
export { default as Subtract } from "./Subtract.png"
export { default as Subtract1 } from "./Subtract1.png"
export { default as EVcarCover } from "./EVcarCover.png"
export { default as Blackev0 } from "./blackev0.jpg"
export { default as Blackev1 } from "./blackev1.jpg"
export { default as Blackev2 } from "./blackev2.png"
export { default as Blackev3 } from "./blackev3.jpg"
export { default as Blackev4 } from "./blackev4.jpg"
export { default as Blightev } from "./blightev.jpg"
export { default as Blightev1 } from "./blightev1.jpg"
export { default as Blightev2 } from "./blightev2.jpg"
export { default as Blightev3 } from "./blightev3.jpg"
export { default as Blightev4 } from "./blightev4.png"
export { default as Blightev5 } from "./blightev5.jpg"
export { default as UniversityEDL } from "./EDLUniversar2.png"
export { default as EDLOffice } from "./Banner1.png"
export { default as edlapp } from "./edlapp2.png"
export { default as edlbuilding } from "./building2.png"
export { default as pugcharge } from "./pugcharge.png"
export { default as roottop } from "./rootetop2.png"
